// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type CensorLpmV4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type CensorLpmV6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	CensorMapAllowV4         = "allow_v4"
	CensorMapAllowV6         = "allow_v6"
	CensorMapConfig          = "config"
	CensorMapEvents          = "events"
	CensorMapSockPid         = "sock_pid"
	CensorProgCensorConnect4 = "censor_connect4"
	CensorProgCensorConnect6 = "censor_connect6"
	CensorProgCensorEgress   = "censor_egress"
)

// LoadCensor returns the embedded CollectionSpec for Censor.
func LoadCensor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CensorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Censor: %w", err)
	}

	return spec, err
}

// LoadCensorObjects loads Censor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CensorObjects
//	*CensorPrograms
//	*CensorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCensorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCensor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CensorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CensorSpecs struct {
	CensorProgramSpecs
	CensorMapSpecs
	CensorVariableSpecs
}

// CensorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CensorProgramSpecs struct {
	CensorConnect4 *ebpf.ProgramSpec `ebpf:"censor_connect4"`
	CensorConnect6 *ebpf.ProgramSpec `ebpf:"censor_connect6"`
	CensorEgress   *ebpf.ProgramSpec `ebpf:"censor_egress"`
}

// CensorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CensorMapSpecs struct {
	AllowV4 *ebpf.MapSpec `ebpf:"allow_v4"`
	AllowV6 *ebpf.MapSpec `ebpf:"allow_v6"`
	Config  *ebpf.MapSpec `ebpf:"config"`
	Events  *ebpf.MapSpec `ebpf:"events"`
	SockPid *ebpf.MapSpec `ebpf:"sock_pid"`
}

// CensorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CensorVariableSpecs struct {
}

// CensorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CensorObjects struct {
	CensorPrograms
	CensorMaps
	CensorVariables
}

func (o *CensorObjects) Close() error {
	return _CensorClose(
		&o.CensorPrograms,
		&o.CensorMaps,
	)
}

// CensorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CensorMaps struct {
	AllowV4 *ebpf.Map `ebpf:"allow_v4"`
	AllowV6 *ebpf.Map `ebpf:"allow_v6"`
	Config  *ebpf.Map `ebpf:"config"`
	Events  *ebpf.Map `ebpf:"events"`
	SockPid *ebpf.Map `ebpf:"sock_pid"`
}

func (m *CensorMaps) Close() error {
	return _CensorClose(
		m.AllowV4,
		m.AllowV6,
		m.Config,
		m.Events,
		m.SockPid,
	)
}

// CensorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CensorVariables struct {
}

// CensorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CensorPrograms struct {
	CensorConnect4 *ebpf.Program `ebpf:"censor_connect4"`
	CensorConnect6 *ebpf.Program `ebpf:"censor_connect6"`
	CensorEgress   *ebpf.Program `ebpf:"censor_egress"`
}

func (p *CensorPrograms) Close() error {
	return _CensorClose(
		p.CensorConnect4,
		p.CensorConnect6,
		p.CensorEgress,
	)
}

func _CensorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed censor_bpfel.o
var _CensorBytes []byte
